import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
const artifact = JSON.parse(
  readFileSync("out/ResourceAccounts.sol/ResourceAccounts.json", "utf8"),
);
mkdirSync("packages/abi", { recursive: true });
const json = JSON.stringify(artifact.abi, null, 2) + "\n";
const ts =
  "// Generated by scripts/export-abi.mjs from the compiled contract.\nexport const resourceAccountsAbi = " +
  JSON.stringify(artifact.abi) +
  " as const;\n";
for (const [path, content] of [
  ["packages/abi/ResourceAccounts.json", json],
  ["packages/abi/index.ts", ts],
]) {
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== content)
      throw new Error("Stale ABI: " + path);
  } else writeFileSync(path, content);
}
